baseurl = "http://alexherman.net"
title = "The Subtle Art of Waiting for Lunch"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"

[author]
    name = "Alex Herman"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Technology, Tutorials, Dad Jokes"
  Author = "Alex Herman"
  email = "alex.thehulk.herman@gmail.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/Simulalex"
[[params.social]]
    title = "github"
    url = "https://github.com/Simulalex"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
